# .github/actions/php-cache-restore/action.yaml

name: "PHP Cache Restoration"
description: "Setup a Composer environment and restore cache if any, given a PHP version"

inputs:
  php-version:
    description: "PHP version to use, default to 7.4"
    required: true
    default: "7.4"
outputs:
  cache-hit:
    description: "Forward actions/cache cache-hit output"
    value: ${{ steps.composer-cache.outputs.cache-hit }}

runs:
  using: "composite" # Mandatory parameter
  steps:

    # Setup a PHP environment given a PHP version
    - name: Use PHP ${{ inputs.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        coverage: xdebug

    - name: Cache Composer Packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        # Make the cache dependencies depending on the PHP version for matrix
        # testing: the compose-lock.json would be the same so an additional
        # criteria is required to distinguish the caches
        key: composer-packages-${{ inputs.php-version }}-${{ hashFiles('**/composer.lock') }}
